# `(sudo) bundle install` will ensure these are present.

# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem 'middleman', '~> 3.3.4'

# Syntax Highlighting
gem 'middleman-syntax'

# Image dimensions
gem 'fastimage'

# Nokigiri for XML modifications
gem 'nokogiri'
